# Generated by Django 2.0.1 on 2018-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='quote',
            field=models.TextField(null=True),
        ),
    ]
